// Builds src/components/icons.tsx from the Iconify Tabler set (MIT).
// Each icon becomes a plain inline-SVG React component with clean paths that
// use currentColor, so colours come from CSS and paths can be animated.
// Run: node scripts/build-icons.mjs
import {readFileSync, writeFileSync} from 'node:fs'
import {getIconData, iconToSVG} from '@iconify/utils'

const set = JSON.parse(readFileSync(new URL('../node_modules/@iconify-json/tabler/icons.json', import.meta.url)))

// Component name -> Tabler icon name. Browse more at https://icon-sets.iconify.design/tabler/
const ICONS = {
  AirConditioning: 'air-conditioning',
  AlertCircle: 'alert-circle',
  Bolt: 'bolt',
  Crane: 'crane',
  Laptop: 'device-laptop',
  Smartphone: 'device-mobile',
  Tv: 'device-tv',
  AlertTriangle: 'alert-triangle',
  Award: 'award',
  Building: 'building',
  Camera: 'camera',
  Copy: 'copy',
  Folder: 'folder',
  Globe: 'world',
  Lock: 'lock',
  Mail: 'mail',
  Map: 'map',
  MessageCircle: 'message-circle',
  Motorbike: 'motorbike',
  Photo: 'photo',
  Printer: 'printer',
  Receipt: 'receipt',
  Route: 'route',
  Scale: 'scale',
  Upload: 'upload',
  Eye: 'eye',
  Battery: 'battery-2',
  Bell: 'bell',
  CalendarDays: 'calendar',
  CalendarX: 'calendar-x',
  Car: 'car',
  Check: 'check',
  ChevronLeft: 'chevron-left',
  ChevronRight: 'chevron-right',
  CircleCheck: 'circle-check',
  CircleDot: 'circle-dot',
  CircleStop: 'disc',
  CircleUser: 'user-circle',
  ClipboardList: 'clipboard-list',
  Clock: 'clock',
  Cog: 'settings',
  Droplets: 'droplet',
  ExternalLink: 'external-link',
  FileText: 'file-text',
  Home: 'home',
  Info: 'info-circle',
  LayoutGrid: 'layout-grid',
  LocateFixed: 'current-location',
  LogOut: 'logout',
  MapPin: 'map-pin',
  MapPinOff: 'map-pin-off',
  Minus: 'minus',
  Pencil: 'pencil',
  Phone: 'phone',
  Plus: 'plus',
  ScanSearch: 'scan-eye',
  Search: 'search',
  SearchX: 'search-off',
  ShoppingCart: 'shopping-cart',
  Sparkles: 'sparkles',
  Star: 'star',
  Store: 'building-store',
  Trash2: 'trash',
  Wind: 'wind',
  Wrench: 'tool',
  X: 'x',
}

const missing = []
const out = []
for (const [name, id] of Object.entries(ICONS)) {
  const data = getIconData(set, id)
  if (!data) {
    missing.push(id)
    continue
  }
  const {attributes, body} = iconToSVG(data)
  // Paint attributes move to the <svg> root (see icon() below), so CSS and props
  // control colour, fill and stroke width, and each path stays bare.
  const jsx = body
    .replace(/ (fill="none"|stroke="currentColor"|stroke-linecap="round"|stroke-linejoin="round"|stroke-width="2")/g, '')
    .replace(/^<g>(.*)<\/g>$/, '$1')
    .replace(/stroke-linecap/g, 'strokeLinecap')
    .replace(/stroke-linejoin/g, 'strokeLinejoin')
    .replace(/stroke-width/g, 'strokeWidth')
    .replace(/fill-rule/g, 'fillRule')
    .replace(/clip-rule/g, 'clipRule')
  out.push(
    `/** tabler:${id} */\nexport const ${name} = icon('${name}', '${attributes.viewBox}', <>${jsx}</>)`,
  )
}
if (missing.length) {
  console.error('Missing Tabler icons:', missing.join(', '))
  process.exit(1)
}

writeFileSync(
  new URL('../src/components/icons.tsx', import.meta.url),
  `// Generated by scripts/build-icons.mjs from Iconify (Tabler, MIT). Do not edit by hand.
// Add an icon: map a name to a Tabler id in the script, then run it again.
import React from 'react'

export type IconProps = Omit<React.SVGProps<SVGSVGElement>, 'ref'> & {
  size?: number | string
  strokeWidth?: number | string
}

export type Icon = React.FC<IconProps>

function icon(name: string, viewBox: string, paths: React.ReactNode): Icon {
  const C: Icon = ({size = 24, strokeWidth = 2, className, ...rest}) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox={viewBox}
      fill="none"
      stroke="currentColor"
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className ? \`icon \${className}\` : 'icon'}
      focusable="false"
      {...rest}>
      {paths}
    </svg>
  )
  C.displayName = name
  return C
}

${out.join('\n\n')}
`,
)
console.log(`Wrote ${out.length} icons`)
