-- Local / new-project bootstrap for the Kumpooni web app.
-- Run once in Supabase → SQL Editor → New query → Run.
-- Safe to run again: existing objects are left in place.

create extension if not exists pgcrypto;

do $$ begin
  create type public.service_type as enum ('In-Store', 'Home Service', 'OrderDelivery');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public."serviceItemType" as enum ('Product', 'Service');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public."serviceStatus" as enum ('Draft', 'Active', 'Inactive', 'Reviewed', 'Deleted');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.invoice_status as enum ('Paid', 'Unpaid', 'Partially', 'Void', 'Uncollectible', 'Draft', 'Open');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.notification_type as enum (
    'scheduled', 'inprogress', 'awaiting-parts', 'canceled', 'completed',
    'new-order', 'canceled-order', 'completed-order', 'store', 'services', 'updates', 'default'
  );
exception when duplicate_object then null; end $$;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  name text not null,
  img_url text,
  is_archived boolean not null default false
);

create table if not exists public.store (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  address text not null,
  city text not null,
  contact_no text not null,
  latitude double precision not null,
  longitude double precision not null,
  location text,
  business_hours text,
  banner_img text,
  store_img text,
  store_logo text,
  outside_img text,
  tagline text,
  merchant_offers text[],
  metadata jsonb
);

create table if not exists public.store_categories (
  store_id uuid not null references public.store(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (store_id, category_id)
);

create table if not exists public.service (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  category_id bigint not null references public.categories(id),
  store_id uuid references public.store(id) on delete cascade,
  source_id bigint references public.service(id),
  name text not null,
  price numeric not null,
  description text,
  short_description text,
  inclusion text[],
  img_url text,
  unit_measure text,
  minimum_qty integer,
  is_active boolean not null default true,
  is_car_required boolean not null default true,
  service_type public.service_type not null default 'In-Store',
  status public."serviceStatus" not null default 'Active',
  type public."serviceItemType" not null default 'Service'
);

create table if not exists public.brand (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  img_url text
);

create table if not exists public.model (
  id bigint generated by default as identity primary key,
  brand_id bigint references public.brand(id) on delete cascade,
  name text
);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz,
  email text,
  phone text,
  first_name text,
  last_name text,
  full_name text,
  avatar_url text,
  fcm_token text,
  notifications_last_read timestamptz
);

create table if not exists public.vehicle (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  user_id uuid references public.users(id) on delete cascade,
  brand_id bigint references public.brand(id),
  model_id bigint references public.model(id),
  year_model text,
  plate_no text
);

create table if not exists public.repair_order (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  user_id uuid not null references public.users(id) on delete cascade,
  store_id uuid not null references public.store(id),
  vehicle_id uuid references public.vehicle(id),
  appointment_date date not null,
  appointment_time text not null,
  arrival_time text,
  reference_no bigint generated by default as identity,
  status public.notification_type default 'scheduled',
  invoice_status public.invoice_status default 'Unpaid',
  priority text,
  internal_notes text,
  total_cost numeric
);

create table if not exists public.repair_order_line (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  repair_order_id uuid references public.repair_order(id) on delete cascade,
  service_id bigint references public.service(id),
  store_id uuid not null references public.store(id),
  name text,
  price numeric,
  quantity integer not null default 1
);

create table if not exists public.repair_order_part (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  repair_order_id uuid not null references public.repair_order(id) on delete cascade,
  repair_order_line_id bigint references public.repair_order_line(id),
  store_id uuid not null references public.store(id),
  part_id bigint,
  name text not null,
  part_no text,
  unit_measure text,
  price numeric not null,
  cost numeric,
  quantity integer not null default 1
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  user_id uuid references public.users(id) on delete cascade,
  store_id uuid references public.store(id),
  repair_order_id uuid references public.repair_order(id),
  service_id bigint references public.service(id),
  rating integer,
  content text
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  user_id uuid references public.users(id) on delete cascade,
  store_id uuid references public.store(id),
  repair_order_id uuid references public.repair_order(id),
  type public.notification_type not null default 'default',
  description text,
  metadata jsonb,
  is_public boolean default false,
  is_read boolean not null default false,
  read_at timestamptz
);

create index if not exists service_name_fts on public.service using gin (to_tsvector('english', name));
create index if not exists service_store_source on public.service (store_id, source_id);

-- Distance in metres (sphere).
create or replace function public.dist_meters(lat1 double precision, lng1 double precision, lat2 double precision, lng2 double precision)
returns double precision
language sql
immutable
as $$
  select 6371000 * acos(least(1::double precision, greatest(-1::double precision,
    cos(radians(lat1)) * cos(radians(lat2)) * cos(radians(lng2) - radians(lng1))
    + sin(radians(lat1)) * sin(radians(lat2))
  )));
$$;

create or replace function public.search_nearby_stores(_lng double precision, _lat double precision, _search text)
returns table (
  id uuid,
  name text,
  longitude double precision,
  latitude double precision,
  business_hours text,
  store_img text,
  contact_no text,
  address text,
  city text,
  outside_img text,
  merchant_offers text[],
  dist_meters double precision,
  order_total bigint,
  review_count bigint,
  store_rating double precision
)
language sql
stable
as $$
  select
    s.id,
    s.name,
    s.longitude,
    s.latitude,
    s.business_hours,
    s.store_img,
    s.contact_no,
    s.address,
    s.city,
    s.outside_img,
    s.merchant_offers,
    public.dist_meters(_lat, _lng, s.latitude, s.longitude),
    (select count(*) from public.repair_order ro where ro.store_id = s.id),
    (select count(*) from public.reviews r where r.store_id = s.id),
    coalesce((select avg(r.rating)::double precision from public.reviews r where r.store_id = s.id), 0)
  from public.store s
  where coalesce(trim(_search), '') = ''
     or s.name ilike '%' || trim(_search) || '%'
     or s.city ilike '%' || trim(_search) || '%'
     or s.address ilike '%' || trim(_search) || '%'
  order by 13;
$$;

create or replace function public.get_nearby_stores(_lat double precision, _lng double precision, _service_ids integer[])
returns table (
  id uuid,
  name text,
  store_img text,
  latitude double precision,
  longitude double precision,
  address text,
  city text,
  store_logo text,
  dist_meters double precision,
  metadata jsonb,
  service_ids integer[],
  order_total numeric,
  review_count bigint,
  rating double precision,
  services jsonb[],
  total numeric
)
language sql
stable
as $$
  select
    s.id,
    s.name,
    s.store_img,
    s.latitude,
    s.longitude,
    s.address,
    s.city,
    s.store_logo,
    public.dist_meters(_lat, _lng, s.latitude, s.longitude),
    s.metadata,
    array_agg(svc.source_id order by svc.id)::integer[],
    coalesce((select sum(ro.total_cost) from public.repair_order ro where ro.store_id = s.id), 0),
    (select count(*) from public.reviews r where r.store_id = s.id),
    coalesce((select avg(r.rating)::double precision from public.reviews r where r.store_id = s.id), 4.6),
    array_agg(to_jsonb(svc) order by svc.id),
    sum(svc.price)
  from public.store s
  join public.service svc on svc.store_id = s.id
    and svc.is_active
    and svc.source_id = any(_service_ids)
  group by s.id
  having count(*) = cardinality(_service_ids);
$$;

create or replace function public.get_store_available_slots(storeid uuid)
returns table (
  available_date date,
  available_timeslots text[],
  week_day text
)
language sql
stable
as $$
  select
    d::date,
    array['09:00','10:00','11:00','13:00','14:00','15:00','16:00']::text[],
    to_char(d, 'Dy')
  from generate_series(current_date + 1, current_date + 21, interval '1 day') as d
  where extract(isodow from d) < 7
    and exists (select 1 from public.store s where s.id = storeid);
$$;

create or replace function public.get_notifications(user_id_param uuid)
returns table (date text, data jsonb)
language sql
stable
as $$
  select
    to_char(n.created_at, 'YYYY-MM-DD'),
    jsonb_agg(
      jsonb_build_object(
        'id', n.id,
        'type', n.type,
        'content', n.description,
        'user_id', n.user_id,
        'read_at', n.read_at,
        'created_at', n.created_at,
        'store_id', n.store_id,
        'store_name', s.name,
        'repair_order_id', n.repair_order_id,
        'is_read', n.is_read
      )
      order by n.created_at desc
    )
  from public.notifications n
  left join public.store s on s.id = n.store_id
  where n.user_id = user_id_param
  group by 1
  order by 1 desc;
$$;

create or replace function public.create_repair_order(
  user_id uuid,
  store_id uuid,
  appointment_date date,
  appointment_time text,
  services_arg jsonb,
  vehicle_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid := gen_random_uuid();
  ref_no bigint;
  item jsonb;
  svc public.service%rowtype;
  qty integer;
  total numeric := 0;
begin
  if auth.uid() is not null and auth.uid() <> user_id then
    raise exception 'Not allowed';
  end if;

  insert into public.users (id) values (user_id) on conflict (id) do nothing;

  insert into public.repair_order (id, user_id, store_id, vehicle_id, appointment_date, appointment_time, status)
  values (new_id, user_id, store_id, vehicle_id, appointment_date, appointment_time, 'scheduled')
  returning reference_no into ref_no;

  for item in select * from jsonb_array_elements(services_arg)
  loop
    qty := coalesce((item->>'quantity')::int, 1);
    select * into svc from public.service where id = (item->>'service_id')::bigint;
    if not found then
      raise exception 'Service not found';
    end if;
    insert into public.repair_order_line (repair_order_id, service_id, store_id, name, price, quantity)
    values (new_id, svc.id, store_id, svc.name, svc.price, qty);
    total := total + svc.price * qty;
  end loop;

  update public.repair_order set total_cost = total where id = new_id;
  return jsonb_build_object('repair_order_id', new_id, 'reference_no', ref_no::text);
end;
$$;

create or replace function public.delete_user()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not signed in';
  end if;
  delete from auth.users where id = auth.uid();
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, phone, email, first_name, last_name, full_name)
  values (
    new.id,
    new.phone,
    new.email,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    coalesce(new.raw_user_meta_data->>'full_name', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

alter table public.categories enable row level security;
alter table public.store enable row level security;
alter table public.store_categories enable row level security;
alter table public.service enable row level security;
alter table public.brand enable row level security;
alter table public.model enable row level security;
alter table public.users enable row level security;
alter table public.vehicle enable row level security;
alter table public.repair_order enable row level security;
alter table public.repair_order_line enable row level security;
alter table public.repair_order_part enable row level security;
alter table public.reviews enable row level security;
alter table public.notifications enable row level security;

do $$ begin
  create policy categories_read on public.categories for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy store_read on public.store for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy store_categories_read on public.store_categories for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy service_read on public.service for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy brand_read on public.brand for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy model_read on public.model for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy users_own_read on public.users for select using (auth.uid() = id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy users_own_update on public.users for update using (auth.uid() = id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy users_own_insert on public.users for insert with check (auth.uid() = id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy vehicle_own on public.vehicle for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy orders_own on public.repair_order for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy order_lines_own on public.repair_order_line for select
    using (exists (select 1 from public.repair_order ro where ro.id = repair_order_id and ro.user_id = auth.uid()));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy order_parts_own on public.repair_order_part for select
    using (exists (select 1 from public.repair_order ro where ro.id = repair_order_id and ro.user_id = auth.uid()));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy reviews_read on public.reviews for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy reviews_insert on public.reviews for insert with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy notifications_own on public.notifications for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

grant usage on schema public to anon, authenticated;
grant select on public.categories, public.store, public.store_categories, public.service, public.brand, public.model, public.reviews to anon, authenticated;
grant select, insert, update, delete on public.users, public.vehicle, public.repair_order, public.repair_order_line, public.repair_order_part, public.notifications to authenticated;
grant usage, select on all sequences in schema public to authenticated, anon;
grant execute on function public.search_nearby_stores(double precision, double precision, text) to anon, authenticated;
grant execute on function public.get_nearby_stores(double precision, double precision, integer[]) to anon, authenticated;
grant execute on function public.get_store_available_slots(uuid) to anon, authenticated;
grant execute on function public.get_notifications(uuid) to authenticated;
grant execute on function public.create_repair_order(uuid, uuid, date, text, jsonb, uuid) to authenticated;
grant execute on function public.delete_user() to authenticated;

-- Sample catalogue (Philippines shops). Re-run keeps the same ids.
insert into public.categories (id, name, img_url, is_archived) values
  (1, 'Oil change', null, false),
  (2, 'Brakes', null, false),
  (3, 'Aircon', null, false),
  (4, 'Battery', null, false),
  (5, 'Tires', null, false),
  (6, 'Tune-up', null, false),
  (7, 'Detailing', null, false),
  (8, 'Diagnostics', null, false)
on conflict (id) do update set name = excluded.name, is_archived = false;

insert into public.service (id, category_id, store_id, source_id, name, price, short_description, description, inclusion, is_active, is_car_required, type, status, service_type) values
  (1, 1, null, null, 'Engine oil change', 1500, 'Oil and filter change', 'Drain and replace engine oil. New oil filter included.', array['Oil','Filter','Labour'], true, true, 'Service', 'Active', 'In-Store'),
  (2, 1, null, null, 'Fully synthetic oil change', 2800, 'Full synthetic oil', 'Full synthetic oil and filter for longer drain intervals.', array['Full synthetic oil','Filter','Labour'], true, true, 'Service', 'Active', 'In-Store'),
  (3, 2, null, null, 'Brake pad replacement', 3200, 'Front or rear pads', 'Replace worn brake pads. Rotors inspected.', array['Pads','Labour'], true, true, 'Service', 'Active', 'In-Store'),
  (4, 3, null, null, 'Aircon cleaning', 1800, 'Evaporator clean', 'Clean evaporator and cabin filter. Check gas.', array['Cleaning','Cabin filter check'], true, true, 'Service', 'Active', 'In-Store'),
  (5, 3, null, null, 'Aircon recharge', 2500, 'Add refrigerant', 'Recover, vacuum and recharge aircon gas.', array['Refrigerant','Labour'], true, true, 'Service', 'Active', 'In-Store'),
  (6, 4, null, null, 'Battery test and replace', 4500, 'New battery if needed', 'Load test. Replace battery if it fails.', array['Test','Battery (if needed)'], true, true, 'Service', 'Active', 'In-Store'),
  (7, 5, null, null, 'Tire rotation and balance', 800, 'Four wheels', 'Rotate and balance all four tires.', array['Rotation','Balance'], true, true, 'Service', 'Active', 'In-Store'),
  (8, 6, null, null, 'Engine tune-up', 3500, 'Plugs and filters', 'Spark plugs, air filter and idle check.', array['Plugs','Air filter','Labour'], true, true, 'Service', 'Active', 'In-Store'),
  (9, 7, null, null, 'Interior detailing', 2200, 'Cabin clean', 'Vacuum, wipe down and fabric clean.', array['Vacuum','Wipe','Fabric clean'], true, false, 'Service', 'Active', 'In-Store'),
  (10, 8, null, null, 'Computer diagnostics', 1200, 'Scan codes', 'OBD scan and a written report.', array['Scan','Report'], true, true, 'Service', 'Active', 'In-Store')
on conflict (id) do update set name = excluded.name, price = excluded.price, is_active = true;

select setval(pg_get_serial_sequence('public.service', 'id'), (select max(id) from public.service));
select setval(pg_get_serial_sequence('public.categories', 'id'), (select max(id) from public.categories));

insert into public.store (id, name, address, city, contact_no, latitude, longitude, business_hours, tagline, store_img, store_logo) values
  ('5fb344c6-f65c-444f-8aa5-2396508356fd', 'Auto-Mate', 'BGC, Taguig', 'Taguig', '09171234567', 14.5503, 121.0509, 'Mon–Sat 8:00–18:00', 'Same-day service', null, null),
  ('11111111-1111-1111-1111-111111111111', 'Makati Auto Care', 'Poblacion, Makati', 'Makati', '09181234567', 14.5636, 121.0265, 'Mon–Sat 8:00–17:00', 'Honest prices', null, null),
  ('22222222-2222-2222-2222-222222222222', 'QC Pit Stop', 'Timog Ave, Quezon City', 'Quezon City', '09191234567', 14.6370, 121.0308, 'Daily 7:00–19:00', 'Open late', null, null),
  ('33333333-3333-3333-3333-333333333333', 'Cebu Car Hub', 'IT Park, Cebu City', 'Cebu City', '09201234567', 10.3270, 123.9060, 'Mon–Sat 8:00–18:00', 'Visayas ready', null, null)
on conflict (id) do update set name = excluded.name, latitude = excluded.latitude, longitude = excluded.longitude;

insert into public.store_categories (store_id, category_id)
select s.id, c.id from public.store s cross join public.categories c
on conflict do nothing;

-- Shop copies of the catalogue. Prices vary so compare-quotes has something to show.
insert into public.service (category_id, store_id, source_id, name, price, short_description, description, inclusion, is_active, is_car_required, type, status, service_type)
select
  cat.id,
  st.id,
  cat_svc.id,
  cat_svc.name,
  round(cat_svc.price * st.mult, 0),
  cat_svc.short_description,
  cat_svc.description,
  cat_svc.inclusion,
  true,
  cat_svc.is_car_required,
  'Service',
  'Active',
  'In-Store'
from public.service cat_svc
join public.categories cat on cat.id = cat_svc.category_id
join (
  select id, 1.00::numeric as mult from public.store where id = '5fb344c6-f65c-444f-8aa5-2396508356fd'
  union all
  select id, 1.12 from public.store where id = '11111111-1111-1111-1111-111111111111'
  union all
  select id, 0.92 from public.store where id = '22222222-2222-2222-2222-222222222222'
  union all
  select id, 1.05 from public.store where id = '33333333-3333-3333-3333-333333333333'
) st on true
where cat_svc.store_id is null
  and not exists (
    select 1 from public.service x
    where x.store_id = st.id and x.source_id = cat_svc.id
  );

insert into public.brand (id, name) values
  (1, 'Toyota'), (2, 'Honda'), (3, 'Mitsubishi'), (4, 'Ford'), (5, 'Hyundai'), (6, 'Nissan'), (7, 'BYD')
on conflict (id) do update set name = excluded.name;

insert into public.model (id, brand_id, name) values
  (1, 1, 'Vios'), (2, 1, 'Fortuner'), (3, 1, 'Innova'),
  (4, 2, 'Civic'), (5, 2, 'CR-V'),
  (6, 3, 'Montero Sport'), (7, 3, 'Mirage'),
  (8, 4, 'Ranger'), (9, 4, 'Everest'),
  (10, 5, 'Tucson'), (11, 6, 'Navara'), (12, 7, 'Atto 3')
on conflict (id) do update set name = excluded.name, brand_id = excluded.brand_id;

select setval(pg_get_serial_sequence('public.categories', 'id'), (select max(id) from public.categories));
select setval(pg_get_serial_sequence('public.service', 'id'), (select max(id) from public.service));
select setval(pg_get_serial_sequence('public.brand', 'id'), (select max(id) from public.brand));
select setval(pg_get_serial_sequence('public.model', 'id'), (select max(id) from public.model));
