const location = {
  id: '114398896',
  city_id: 714,
  city: 'Bacolod',
  city_name: null,
  area_id: null,
  areas: null,
  address_line1: 'Bacolod-San Carlos City Rd',
  address_line2: 'Bacolod-San Carlos City Rd, 6100 Bacolod City, Philippines',
  address_line3: null,
  address_line4: null,
  address_line5: null,
  address_other: null,
  room: null,
  flat_number: null,
  structure: null,
  building: null,
  intercom: null,
  entrance: null,
  floor: null,
  district: null,
  postcode: null,
  meta: '{"dynamic_fields":{},"locale":"en_PH","provider":"here"}',
  company: null,
  longitude: 122.93701541,
  latitude: 10.64676711,
  is_delivery_available: true,
  delivery_instructions: null,
  title: null,
  label: null,
  formatted_customer_address:
    'Bacolod-San Carlos City Rd, 6100 Bacolod City, Philippines Bacolod-San Carlos City Rd Bacolod',
  campus: null,
  corporate_reference_id: null,
  form_id: '9dtlk6mzdc56',
  country_code: 'PH',
  created_at: '2024-02-23T02:52:18Z',
  updated_at: '2024-02-23T02:52:18Z',
  location_type: 'polygon',
  object_type: 'saved address',
  type: '0',
  phone_country_code: null,
  phone_number: null,
  formatted_address: null,
  is_same_as_requested_location: null,
  block: null,
  property_type: null,
  place_name: null,
  landmark: null,
  meeting_point: null,
  door_code: null,
  free_text_address: null,
  gate: null,
  entrance_picture: null,
}
