// Generated by scripts/build-icons.mjs from Iconify (Tabler, MIT). Do not edit by hand.
// Add an icon: map a name to a Tabler id in the script, then run it again.
import React from 'react'

export type IconProps = Omit<React.SVGProps<SVGSVGElement>, 'ref'> & {
  size?: number | string
  strokeWidth?: number | string
}

export type Icon = React.FC<IconProps>

function icon(name: string, viewBox: string, paths: React.ReactNode): Icon {
  const C: Icon = ({size = 24, strokeWidth = 2, className, ...rest}) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox={viewBox}
      fill="none"
      stroke="currentColor"
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className ? `icon ${className}` : 'icon'}
      focusable="false"
      {...rest}>
      {paths}
    </svg>
  )
  C.displayName = name
  return C
}

/** tabler:air-conditioning */
export const AirConditioning = icon('AirConditioning', '0 0 24 24', <><path d="M8 16a3 3 0 0 1-3 3m11-3a3 3 0 0 0 3 3m-7-3v4M3 7a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M7 13v-3a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v3"/></>)

/** tabler:alert-circle */
export const AlertCircle = icon('AlertCircle', '0 0 24 24', <><path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0-18 0m9-4v4m0 4h.01"/></>)

/** tabler:bolt */
export const Bolt = icon('Bolt', '0 0 24 24', <><path d="M13 3v7h6l-8 11v-7H5z"/></>)

/** tabler:crane */
export const Crane = icon('Crane', '0 0 24 24', <><path d="M6 21h6m-3 0V3L3 9h18M9 3l10 6"/><path d="M17 9v4a2 2 0 1 1-2 2"/></>)

/** tabler:device-laptop */
export const Laptop = icon('Laptop', '0 0 24 24', <><path d="M3 19h18M5 7a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1z"/></>)

/** tabler:device-mobile */
export const Smartphone = icon('Smartphone', '0 0 24 24', <><path d="M6 5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2zm5-1h2m-1 13v.01"/></>)

/** tabler:device-tv */
export const Tv = icon('Tv', '0 0 24 24', <><path d="M3 9a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2zm13-6l-4 4l-4-4"/></>)

/** tabler:alert-triangle */
export const AlertTriangle = icon('AlertTriangle', '0 0 24 24', <><path d="M12 9v4m-1.637-9.409L2.257 17.125a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636-2.87L13.637 3.59a1.914 1.914 0 0 0-3.274 0M12 16h.01"/></>)

/** tabler:award */
export const Award = icon('Award', '0 0 24 24', <><path d="M6 9a6 6 0 1 0 12 0A6 6 0 1 0 6 9"/><path d="m12 15l3.4 5.89l1.598-3.233l3.598.232l-3.4-5.889M6.802 12l-3.4 5.89L7 17.657l1.598 3.232l3.4-5.889"/></>)

/** tabler:building */
export const Building = icon('Building', '0 0 24 24', <><path d="M3 21h18M9 8h1m-1 4h1m-1 4h1m4-8h1m-1 4h1m-1 4h1M5 21V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16"/></>)

/** tabler:camera */
export const Camera = icon('Camera', '0 0 24 24', <><path d="M5 7h1a2 2 0 0 0 2-2a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1a2 2 0 0 0 2 2h1a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2"/><path d="M9 13a3 3 0 1 0 6 0a3 3 0 0 0-6 0"/></>)

/** tabler:copy */
export const Copy = icon('Copy', '0 0 24 24', <><path d="M7 9.667A2.667 2.667 0 0 1 9.667 7h8.666A2.667 2.667 0 0 1 21 9.667v8.666A2.667 2.667 0 0 1 18.333 21H9.667A2.667 2.667 0 0 1 7 18.333z"/><path d="M4.012 16.737A2 2 0 0 1 3 15V5c0-1.1.9-2 2-2h10c.75 0 1.158.385 1.5 1"/></>)

/** tabler:folder */
export const Folder = icon('Folder', '0 0 24 24', <><path d="M5 4h4l3 3h7a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2"/></>)

/** tabler:world */
export const Globe = icon('Globe', '0 0 24 24', <><path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0-18 0m.6-3h16.8M3.6 15h16.8"/><path d="M11.5 3a17 17 0 0 0 0 18m1-18a17 17 0 0 1 0 18"/></>)

/** tabler:lock */
export const Lock = icon('Lock', '0 0 24 24', <><path d="M5 13a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2z"/><path d="M11 16a1 1 0 1 0 2 0a1 1 0 0 0-2 0m-3-5V7a4 4 0 1 1 8 0v4"/></>)

/** tabler:mail */
export const Mail = icon('Mail', '0 0 24 24', <><path d="M3 7a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="m3 7l9 6l9-6"/></>)

/** tabler:map */
export const Map = icon('Map', '0 0 24 24', <><path d="m3 7l6-3l6 3l6-3v13l-6 3l-6-3l-6 3zm6-3v13m6-10v13"/></>)

/** tabler:message-circle */
export const MessageCircle = icon('MessageCircle', '0 0 24 24', <><path d="m3 20l1.3-3.9C1.976 12.663 2.874 8.228 6.4 5.726c3.526-2.501 8.59-2.296 11.845.48c3.255 2.777 3.695 7.266 1.029 10.501S11.659 20.922 7.7 19z"/></>)

/** tabler:motorbike */
export const Motorbike = icon('Motorbike', '0 0 24 24', <><path d="M2 16a3 3 0 1 0 6 0a3 3 0 1 0-6 0m14 0a3 3 0 1 0 6 0a3 3 0 1 0-6 0m-8.5-2h5l4-4H6m1.5 4l4-4"/><path d="M13 6h2l1.5 3l2 4"/></>)

/** tabler:photo */
export const Photo = icon('Photo', '0 0 24 24', <><path d="M15 8h.01M3 6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3v12a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3z"/><path d="m3 16l5-5c.928-.893 2.072-.893 3 0l5 5"/><path d="m14 14l1-1c.928-.893 2.072-.893 3 0l3 3"/></>)

/** tabler:printer */
export const Printer = icon('Printer', '0 0 24 24', <><path d="M17 17h2a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h2m10-8V5a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2v4"/><path d="M7 15a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2z"/></>)

/** tabler:receipt */
export const Receipt = icon('Receipt', '0 0 24 24', <><path d="M5 21V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16l-3-2l-2 2l-2-2l-2 2l-2-2zM9 7h6m-6 4h6m-2 4h2"/></>)

/** tabler:route */
export const Route = icon('Route', '0 0 24 24', <><path d="M3 19a2 2 0 1 0 4 0a2 2 0 0 0-4 0M19 7a2 2 0 1 0 0-4a2 2 0 0 0 0 4m-8 12h5.5a3.5 3.5 0 0 0 0-7h-8a3.5 3.5 0 0 1 0-7H13"/></>)

/** tabler:scale */
export const Scale = icon('Scale', '0 0 24 24', <><path d="M7 20h10M6 6l6-1l6 1m-6-3v17m-3-8L6 6l-3 6a3 3 0 0 0 6 0m12 0l-3-6l-3 6a3 3 0 0 0 6 0"/></>)

/** tabler:upload */
export const Upload = icon('Upload', '0 0 24 24', <><path d="M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2M7 9l5-5l5 5m-5-5v12"/></>)

/** tabler:eye */
export const Eye = icon('Eye', '0 0 24 24', <><path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0-4 0"/><path d="M21 12q-3.6 6-9 6t-9-6q3.6-6 9-6t9 6"/></>)

/** tabler:battery-2 */
export const Battery = icon('Battery', '0 0 24 24', <><path d="M6 7h11a2 2 0 0 1 2 2v.5a.5.5 0 0 0 .5.5a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5a.5.5 0 0 0-.5.5v.5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2m1 3v4m3-4v4"/></>)

/** tabler:bell */
export const Bell = icon('Bell', '0 0 24 24', <><path d="M10 5a2 2 0 1 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3H4a4 4 0 0 0 2-3v-3a7 7 0 0 1 4-6M9 17v1a3 3 0 0 0 6 0v-1"/></>)

/** tabler:calendar */
export const CalendarDays = icon('CalendarDays', '0 0 24 24', <><path d="M4 7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zm12-4v4M8 3v4m-4 4h16m-9 4h1m0 0v3"/></>)

/** tabler:calendar-x */
export const CalendarX = icon('CalendarX', '0 0 24 24', <><path d="M13 21H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v6.5M16 3v4M8 3v4m-4 4h16m2 11l-5-5m0 5l5-5"/></>)

/** tabler:car */
export const Car = icon('Car', '0 0 24 24', <><path d="M5 17a2 2 0 1 0 4 0a2 2 0 1 0-4 0m10 0a2 2 0 1 0 4 0a2 2 0 1 0-4 0"/><path d="M5 17H3v-6l2-5h9l4 5h1a2 2 0 0 1 2 2v4h-2m-4 0H9m-6-6h15m-6 0V6"/></>)

/** tabler:check */
export const Check = icon('Check', '0 0 24 24', <><path d="m5 12l5 5L20 7"/></>)

/** tabler:chevron-left */
export const ChevronLeft = icon('ChevronLeft', '0 0 24 24', <><path d="m15 6l-6 6l6 6"/></>)

/** tabler:chevron-right */
export const ChevronRight = icon('ChevronRight', '0 0 24 24', <><path d="m9 6l6 6l-6 6"/></>)

/** tabler:circle-check */
export const CircleCheck = icon('CircleCheck', '0 0 24 24', <><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0"/><path d="m9 12l2 2l4-4"/></>)

/** tabler:circle-dot */
export const CircleDot = icon('CircleDot', '0 0 24 24', <><path d="M11 12a1 1 0 1 0 2 0a1 1 0 1 0-2 0"/><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0"/></>)

/** tabler:disc */
export const CircleStop = icon('CircleStop', '0 0 24 24', <><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0"/><path d="M11 12a1 1 0 1 0 2 0a1 1 0 1 0-2 0m-4 0a5 5 0 0 1 5-5m0 10a5 5 0 0 0 5-5"/></>)

/** tabler:user-circle */
export const CircleUser = icon('CircleUser', '0 0 24 24', <><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0"/><path d="M9 10a3 3 0 1 0 6 0a3 3 0 1 0-6 0m-2.832 8.849A4 4 0 0 1 10 16h4a4 4 0 0 1 3.834 2.855"/></>)

/** tabler:clipboard-list */
export const ClipboardList = icon('ClipboardList', '0 0 24 24', <><path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2"/><path d="M9 5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2a2 2 0 0 1-2 2h-2a2 2 0 0 1-2-2m0 7h.01M13 12h2m-6 4h.01M13 16h2"/></>)

/** tabler:clock */
export const Clock = icon('Clock', '0 0 24 24', <><path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0-18 0"/><path d="M12 7v5l3 3"/></>)

/** tabler:settings */
export const Cog = icon('Cog', '0 0 24 24', <><path d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 0 0-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 0 0-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 0 0-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 0 0-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 0 0 1.066-2.573c-.94-1.543.826-3.31 2.37-2.37c1 .608 2.296.07 2.572-1.065"/><path d="M9 12a3 3 0 1 0 6 0a3 3 0 0 0-6 0"/></>)

/** tabler:droplet */
export const Droplets = icon('Droplets', '0 0 24 24', <><path d="M7.502 19.423c2.602 2.105 6.395 2.105 8.996 0s3.262-5.708 1.566-8.546l-4.89-7.26c-.42-.625-1.287-.803-1.936-.397a1.4 1.4 0 0 0-.41.397l-4.893 7.26C4.24 13.715 4.9 17.318 7.502 19.423"/></>)

/** tabler:external-link */
export const ExternalLink = icon('ExternalLink', '0 0 24 24', <><path d="M12 6H6a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-6m-7 1l9-9m-5 0h5v5"/></>)

/** tabler:file-text */
export const FileText = icon('FileText', '0 0 24 24', <><path d="M14 3v4a1 1 0 0 0 1 1h4"/><path d="M17 21H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7l5 5v11a2 2 0 0 1-2 2M9 9h1m-1 4h6m-6 4h6"/></>)

/** tabler:home */
export const Home = icon('Home', '0 0 24 24', <><path d="M5 12H3l9-9l9 9h-2M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-7"/><path d="M9 21v-6a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v6"/></>)

/** tabler:info-circle */
export const Info = icon('Info', '0 0 24 24', <><path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0-18 0m9-3h.01"/><path d="M11 12h1v4h1"/></>)

/** tabler:layout-grid */
export const LayoutGrid = icon('LayoutGrid', '0 0 24 24', <><path d="M4 5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1zm10 0a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-4a1 1 0 0 1-1-1zM4 15a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1zm10 0a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-4a1 1 0 0 1-1-1z"/></>)

/** tabler:current-location */
export const LocateFixed = icon('LocateFixed', '0 0 24 24', <><path d="M9 12a3 3 0 1 0 6 0a3 3 0 1 0-6 0"/><path d="M4 12a8 8 0 1 0 16 0a8 8 0 1 0-16 0m8-10v2m0 16v2m8-10h2M2 12h2"/></>)

/** tabler:logout */
export const LogOut = icon('LogOut', '0 0 24 24', <><path d="M14 8V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2-2v-2"/><path d="M9 12h12l-3-3m0 6l3-3"/></>)

/** tabler:map-pin */
export const MapPin = icon('MapPin', '0 0 24 24', <><path d="M9 11a3 3 0 1 0 6 0a3 3 0 0 0-6 0"/><path d="M17.657 16.657L13.414 20.9a2 2 0 0 1-2.827 0l-4.244-4.243a8 8 0 1 1 11.314 0"/></>)

/** tabler:map-pin-off */
export const MapPinOff = icon('MapPinOff', '0 0 24 24', <><path d="M9.442 9.432a3 3 0 0 0 4.113 4.134M15 11a3 3 0 0 0-3-3"/><path d="M17.152 17.162L13.414 20.9a2 2 0 0 1-2.827 0l-4.244-4.243a8 8 0 0 1-.476-10.794m2.18-1.82a8.003 8.003 0 0 1 10.91 10.912M3 3l18 18"/></>)

/** tabler:minus */
export const Minus = icon('Minus', '0 0 24 24', <><path d="M5 12h14"/></>)

/** tabler:pencil */
export const Pencil = icon('Pencil', '0 0 24 24', <><path d="M4 20h4L18.5 9.5a2.828 2.828 0 1 0-4-4L4 16zm9.5-13.5l4 4"/></>)

/** tabler:phone */
export const Phone = icon('Phone', '0 0 24 24', <><path d="M5 4h4l2 5l-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2"/></>)

/** tabler:plus */
export const Plus = icon('Plus', '0 0 24 24', <><path d="M12 5v14m-7-7h14"/></>)

/** tabler:scan-eye */
export const ScanSearch = icon('ScanSearch', '0 0 24 24', <><path d="M7 12q5-7 10 0M7 12q5 7 10 0m-5 0h-.01M3 7V5a2 2 0 0 1 2-2h2M3 17v2a2 2 0 0 0 2 2h2M17 3h2a2 2 0 0 1 2 2v2m-4 14h2a2 2 0 0 0 2-2v-2"/></>)

/** tabler:search */
export const Search = icon('Search', '0 0 24 24', <><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0-14 0m18 11l-6-6"/></>)

/** tabler:search-off */
export const SearchX = icon('SearchX', '0 0 24 24', <><path d="M5.039 5.062a7 7 0 0 0 9.91 9.89m1.584-2.434a7 7 0 0 0-9.038-9.057M3 3l18 18"/></>)

/** tabler:shopping-cart */
export const ShoppingCart = icon('ShoppingCart', '0 0 24 24', <><path d="M4 19a2 2 0 1 0 4 0a2 2 0 1 0-4 0m11 0a2 2 0 1 0 4 0a2 2 0 1 0-4 0"/><path d="M17 17H6V3H4"/><path d="m6 5l14 1l-1 7H6"/></>)

/** tabler:sparkles */
export const Sparkles = icon('Sparkles', '0 0 24 24', <><path d="M16 18a2 2 0 0 1 2 2a2 2 0 0 1 2-2a2 2 0 0 1-2-2a2 2 0 0 1-2 2m0-12a2 2 0 0 1 2 2a2 2 0 0 1 2-2a2 2 0 0 1-2-2a2 2 0 0 1-2 2M9 18a6 6 0 0 1 6-6a6 6 0 0 1-6-6a6 6 0 0 1-6 6a6 6 0 0 1 6 6"/></>)

/** tabler:star */
export const Star = icon('Star', '0 0 24 24', <><path d="m12 17.75l-6.172 3.245l1.179-6.873l-5-4.867l6.9-1l3.086-6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z"/></>)

/** tabler:building-store */
export const Store = icon('Store', '0 0 24 24', <><path d="M3 21h18M3 7v1a3 3 0 0 0 6 0V7m0 1a3 3 0 0 0 6 0V7m0 1a3 3 0 0 0 6 0V7H3l2-4h14l2 4M5 21V10.85M19 21V10.85M9 21v-4a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v4"/></>)

/** tabler:trash */
export const Trash2 = icon('Trash2', '0 0 24 24', <><path d="M4 7h16m-10 4v6m4-6v6M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l1-12M9 7V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v3"/></>)

/** tabler:wind */
export const Wind = icon('Wind', '0 0 24 24', <><path d="M5 8h8.5a2.5 2.5 0 1 0-2.34-3.24M3 12h15.5a2.5 2.5 0 1 1-2.34 3.24M4 16h5.5a2.5 2.5 0 1 1-2.34 3.24"/></>)

/** tabler:tool */
export const Wrench = icon('Wrench', '0 0 24 24', <><path d="M7 10h3V7L6.5 3.5a6 6 0 0 1 8 8l6 6a2 2 0 0 1-3 3l-6-6a6 6 0 0 1-8-8z"/></>)

/** tabler:x */
export const X = icon('X', '0 0 24 24', <><path d="M18 6L6 18M6 6l12 12"/></>)
