steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}
      - --build-arg=VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}
      - --build-arg=VITE_GOOGLE_MAPS_KEY=${_VITE_GOOGLE_MAPS_KEY}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
